taskproject/urls.py
from django.urls import path
from taskapp import views
from taskapp.views import TaskListView, TaskCreateView, TaskPreviousListView, TaskDetailView, \
    ChecklistCreateView, ChecklistUpdateView, ChecklistDeleteView, TaskDeleteView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.index, name="index"),
    path('', TaskListView.as_view(), name="index"),
    path('task/', TaskCreateView.as_view(), name="create-task"),
    path('previous/', TaskPreviousListView.as_view(), name="previous"),
    path('task/<int:task_id>/', TaskDetailView.as_view(), name="view-task"),
    path('task/<int:task_id>/item/', ChecklistCreateView.as_view(), name="create-item"),
    path('task/<int:task_id>/item/<int:check_id>/', ChecklistUpdateView.as_view(), name="check-item"),

    path('task/<int:task_id>/delete/', TaskDeleteView.as_view(), name="delete-task"),
    path('task/<int:task_id>/item/<int:check_id>/delete/', ChecklistDeleteView.as_view(), name="delete-item"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Task(models.Model):
    class TaskType(models.TextChoices):
        JOB = 'JOB', _('업무')
        HEALTH = 'HEALTH', _('건강')
        SOCIAL = 'SOCIAL', _('사회')

    title = models.CharField(max_length=50, null=False)
    type = models.CharField(
        choices=TaskType.choices,
        max_length=10,
        default=TaskType.JOB
    )
    due = models.DateTimeField(null=False)
    created_at = models.DateTimeField(auto_now_add=True, null=False)


class ChecklistItem(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, null=False)
    checked = models.BooleanField(null=False, default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=False)

taskapp/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin
from .models import Task, ChecklistItem
from django.utils import timezone
from django.core.paginator import Paginator


def index(request):
    context = {}
    return render(request, 'pages/index.html', context)


class TaskListView(TemplateView):
    template_name = 'pages/task_list.html'

    def get_context_data(self, **kwargs):
        tasks = Task.objects.filter(due__gte=timezone.now()).order_by('-due').all()
        paginator = Paginator(tasks, 4)
        page_number = self.request.GET.get('page', '1')
        paging = paginator.get_page(page_number)

        return {
            'paging': paging
        }


class TaskCreateView(CreateView):
    model = Task
    fields = ['title', 'type', 'due']
    template_name = 'pages/task_create.html'
    success_url = '/'


class TaskPreviousListView(ListView):
    model = Task
    template_name = 'pages/task_previous_list.html'
    queryset = Task.objects.filter(due__lt=timezone.now()).order_by('-due')
    paginate_by = 4


class TaskDetailView(SingleObjectMixin, ListView):
    template_name = 'pages/task_detail.html'
    pk_url_kwarg = 'task_id'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Task.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return ChecklistItem.objects.filter(task=self.object).all()


class ChecklistCreateView(CreateView):
    model = ChecklistItem
    fields = ['content']
    template_name = 'pages/checklist_create.html'
    success_url = '/task/'

    def get_success_url(self):
        return self.success_url + str(self.kwargs['task_id']) + '/'

    def form_valid(self, form):
        data = form.save(commit=False)
        data.task = Task.objects.get(id=self.kwargs['task_id'])
        data.save()
        return redirect(self.get_success_url())


class ChecklistUpdateView(UpdateView):
    model = ChecklistItem
    fields = ['checked']
    template_name = 'pages/checklist_update.html'
    success_url = '/task/'
    pk_url_kwarg = 'check_id'

    def get(self, request, *args, **kwargs):
        data = super().get_object()
        data.checked = not data.checked
        data.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('view-task', kwargs={'task_id': str(self.kwargs['task_id'])})


class ChecklistDeleteView(DeleteView):
    model = ChecklistItem
    pk_url_kwarg = 'check_id'
    template_name = 'pages/checklist_delete.html'
    success_url = '/task/'

    def get_success_url(self):
        return reverse('view-task', kwargs={'task_id': str(self.kwargs['task_id'])})


class TaskDeleteView(DeleteView):
    model = Task
    pk_url_kwarg = 'task_id'
    template_name = 'pages/task_delete.html'
    success_url = '/'

taskapp/templates/common.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}할 일{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="/"><span class="navbar-brand mb-0 h1">TASKS</span></a>

            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create-task' %}">
                        <button class="btn btn-dark">
                            할 일 추가
                        </button>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'previous' %}">
                        <button class="btn btn-secondary">
                            이전 할 일
                        </button>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    {% if messages %}
    <div class="mt-2">
        {% for message in messages %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="mt-2">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

taskapp/templates/pages/checklist_create.html
{% extends "common.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary float-right">추가하기</button>
        </div>
    </div>
</form>
{% endblock %}

taskapp/templates/pages/checklist_delete.html
{% extends "common.html" %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            <p>체크리스트 "{{ object.content }}"를 삭제하시겠습니까?</p>
            <button type="submit" class="btn btn-danger float-right">삭제</button>
        </div>
    </div>
</form>
{% endblock %}

taskapp/templates/pages/checklist_update.html
{% extends "common.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary float-right">수정하기</button>
        </div>
    </div>
</form>
{% endblock %}

taskapp/templates/pages/index.html
{% extends "common.html" %}

{% block content %}
<div class="row mt-2">
    테스트
</div>
{% endblock %}

taskapp/templates/pages/task_create.html
{% extends "common.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post" action="{% url 'create-task' %}">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">추가하기</button>
        </div>
    </div>
</form>
<script>
    window.onload = function() {
        flatpickr('input[name="due"]', {enableTime: true});
    }
</script>
{% endblock %}

taskapp/templates/pages/task_delete.html
{% extends "common.html" %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            <p>할 일 "{{ object.title }}"를 삭제하시겠습니까?</p>
            <button type="submit" class="btn btn-danger float-right">삭제</button>
        </div>
    </div>
</form>
{% endblock %}

taskapp/templates/pages/task_detail.html
{% extends "common.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12">
        <h4 class="mt-2 p-2">
            <span class="badge badge-info">
                {{ object.get_type_display }}
            </span>
            {{ object.title }}
        </h4>
        <dl class="row mt-4 p-2">
            <dt class="col-sm-2">마감일</dt>
            <dd class="col-sm-10">{{ object.due|date:'Y년 m월 d일 H시 i분' }}</dd>
            <dt class="col-sm-2">생성일</dt>
            <dd class="col-sm-10">{{ object.created_at|date:'Y년 m월 d일 H시 i분' }}</dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <a href="{% url 'create-item' object.id %}">
            <button class="btn btn-light">
                <i class="bi bi-plus-square"></i>&nbsp;&nbsp;추가
            </button>
        </a>
    </div>
</div>

<table class="table">
    <tbody>
    {% if object_list %}
    {% for check in object_list %}
        <tr>
            <td style="width:20px;">
                {% if check.checked %}
                <a href="{% url 'check-item' object.id check.id %}">
                <button class="btn btn-link">
                    <i class="bi bi-check-square"></i>
                </button>
                </a>
                {% else %}
                <a href="{% url 'check-item' object.id check.id %}">
                <button class="btn btn-link">
                    <i class="bi bi-square"></i>
                </button>
                </a>
                {% endif %}
            </td>
            <td class="align-middle">
                {{ check.content }}
            </td>
            <td style="width: 20px">
                <a href="{% url 'delete-item' object.id check.id %}">
                    <button class="btn btn-link">
                        <i class="bi bi-x-square"></i>
                    </button>
                </a>
            </td>
        </tr>
    {% endfor %}
    {% else %}
        <tr><td>체크리스트가 없습니다.</td></tr>
    {% endif %}
    </tbody>
</table>
{% endblock %}

taskapp/templates/pages/task_list.html
{% extends "common.html" %}
{% load pagination_tags %}

{% block content %}
<div class="row row-cols-2 row-cols-md-4 g-4 mt-2">
    {% for item in paging %}
    <div class="col">
        <div class="card text-white bg-primary mb-3">
            <div class="card-header">
                {{ item.type }}
                <a href="{% url 'delete-task' item.id %}">
                    <button class="btn btn-outline-dark float-right btn-sm">
                        <i class="bi bi-x-lg"></i>
                    </button>
                </a>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card text">
                    <span class="badge bg-light text-dark">
                        {{ item.due|date:'Y년 m월 d일 H시 i분' }}까지
                    </span>
                </p>
            </div>
            <div class="card-footer">
                <a href="{% url 'view-task' item.id %}">
                    <button class="btn btn-dark float-right">보기</button>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row mt-4">
    <nav class="col-12">
        <ul class="pagination justify-content-center">
            {% if paging.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ paging.previous_page_number }}">이전</a>
            </li>
            {% endif %}

            {% for page in paging|slice_visible_pages %}
            {% if paging.number == page %}
            <li class="page-item active">
                {% else %}
                <li class="page-item">
                {% endif %}
                <a class="page-link" href="?page={{ page }}">
                    {{ page }}
                </a>
            </li>
            {% endfor %}

            {% if paging.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ paging.next_page_number }}">다음</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

taskapp/templates/pages/task_previous_list.html
{% extends "common.html" %}
{% load pagination_tags %}

{% block content %}
<div class="row row-cols-2 row-cols-md-4 g-4 mt-2">
    {% for item in object_list %}
    <div class="col">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header">{{ item.type }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card text">
                    <span class="badge bg-light text-dark">
                        {{ item.due|date:'Y년 m월 d일 H시 i분' }}까지
                    </span>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row mt-4">
    <nav class="col-12">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
            </li>
            {% endif %}

            {% for page in page_obj|slice_visible_pages %}
            {% if page_obj.number == page %}
            <li class="page-item active">
                {% else %}
            <li class="page-item">
                {% endif %}
                <a class="page-link" href="?page={{ page }}">
                    {{ page }}
                </a>
            </li>
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}